version: "3"
services:
  backend:
    container_name: backend
    image: backend
    restart: always
    build: ./backend/
    ports:
      - 9090:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image:  database
    build: ./database/
    environment:
      MYSQL_DATABASE: fresh_cart
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend/
    ports:
      - 80:80
